### ISSUE TITLE
inconsistent variable names

### ISSUE THREAD

**Issue by craigiswayne** [magnetikonline/ghmarkdownrender#3]
line 11: 
`const DOC_ROOT = '/path/to/docroot';`
should be
`const DOCUMENT_ROOT = '/path/to/docroot';`

line 10:
`const GITHUB_TOKEN = 'token';
`should be 
`const GITHUB_PERSONAL_ACCESS_TOKEN = 'token';`

**Comment by magnetikonline** [comment]
Now I feel silly :disappointed: 

Well spotted - fixed in 8df128bce270a2f07e38e14f699a3ca7955057ba.

Thanks!
