### ISSUE TITLE
Add content-type to the nginx location block

### ISSUE THREAD

**Issue by craigiswayne** [magnetikonline/ghmarkdownrender#4]
Referring to your example:
rewrite.nginx.conf

```
location ~ "\.md$" {
	if (!-f $request_filename) {
		return 404;
	}

	if ($query_string = "ghmd") {
		rewrite "^" /path/to/ghmarkdownrender/index.php? last;
	}
}
```

maybe into something like this:

```
location ~ "\.md$" {
	if (!-f $request_filename) {
		return 404;
	}

	if ($query_string = "ghmd") {
        add_header Content-Type text/markdown;
		rewrite "^" /path/to/ghmarkdownrender/index.php? last;
	}
}
```

**Comment by magnetikonline** [comment]
Hello Craig,

   thanks for the suggestion - but what you have I believe to be wrong. When a route of /path/to/file.md?ghmd is called and the script is executed, the return output is rendered markdown - making it `text/html` as a content type.

I think this would be more fitting ```
location ~ "\.md$" {
    if (!-f $request_filename) {
        return 404;
    }

    add_header Content-Type text/markdown;
    if ($query_string = "ghmd") {
        rewrite "^" /path/to/ghmarkdownrender/index.php? last;
    }
}
```

But even then, I don't think this offers too much. Also (at least for my Nginx config's on my dev boxes) I have `.md` mapped to `text/markdown` anyway in `/etc/nginx/mime.types`.

  Pete

**Comment by craigiswayne** [comment]
No problem at all. You are the life saver here! It's not often I stumble
upon something online that makes my life easier. Thank u so much

**Comment by magnetikonline** [comment]
Thanks @craigiswayne - love to receive positive feedback like this! 😄
